const carros = [
{
    id: 1,
    imagem: './img/supra.jpg',
    marca: 'Toyota',
    modelo: 'Supra',
    ano: 'ano: 1998',
    valor: 'valor: 90.000',
  },
{
  id: 2,
  imagem: './img/skyline.webp',
  marca: 'Nissan',
  modelo: 'Skyline',
  ano: 'ano: 1997',
  valor: 'valor: 110.000',
},
{
  id: 3,
  imagem: './img/rx7.jpg',
  marca: 'Mazda',
  modelo: 'RX7',
  ano: 'ano: 1999',
  valor: 'valor: 170.000',
},
{
  id: 4,
  imagem: './img/impreza.jpg',
  marca: 'Subaru',
  modelo: 'Impreza',
  ano: 'ano: 1996',
  valor: 'valor: 100.000',
},
{
  id: 5,
  imagem: './img/lancer.webp',
  marca: 'Mitsubish',
  modelo: 'Lancer',
  ano: 'ano: 2008',
  valor: 'valor: 190.000',
 },
{
  id: 6,
  imagem: './img/nsx.jpg',
  marca: 'Acura',
  modelo: 'NSX',
  ano: 'ano: 1991',
  valor: 'valor: 150.000',
},
{
  id: 7,
  imagem: './img/civic.jpg',
  marca: 'Honda',
  modelo: 'Civic',
  ano: 'ano: 1998',
  valor: 'valor: 50.000',
},
{
  id: 8,
  imagem: './img/ferrari-roma.webp',
  marca: 'Ferrari',
  modelo: 'Roma',
  ano: 'ano: 2019',
  valor: 'valor: 2.000.000',
},
{
  id: 9,
  imagem: './img/jaguar.jpg',
  marca: 'Jaguar',
  modelo: 'Pace',
  ano: 'ano: 2015',
  valor: 'valor: 1.500.000',
},
{
  id: 10,
  imagem: './img/porsche-cayenne-ehybrid.webp',
  marca: 'Porche',
  modelo: 'Hybrid',
  ano: 'ano: 2020',
  valor: 'valor: 560.000',
},
{
  id: 11,
  imagem: './img/Hennessey-H700_Corvette_C8_Stingray.jpg',
  marca: 'Covertte',
  modelo: 'C8',
  ano: 'ano: 2019',
  valor: 'valor: 2.700.000',
},
{
  id: 12,
  imagem: './img/Shelby-GT500-CR-Fibra-de-Carbono-frente.webp',
  marca: 'Mustang',
  modelo: 'Shelby GT500',
  ano: 'ano: 1967',
  valor: 'valor: 200.000',
},
{
  id: 13,
  imagem: './img/bmw-i5.webp',
  marca: 'BMW',
  modelo: 'i5',
  ano: 'ano: 2025',
  valor: 'valor: 900.000',
},
{
  id: 14,
  imagem: './img/050321_aston_martin_DB9_hmed.jpg',
  marca: 'Aston Martin',
  modelo: 'DB9',
  ano: 'ano: 2004',
  valor: 'valor: 2.500.000',
},
{
  id: 15,
  imagem: './img/avaliacao-mercedes-benz-c-180-exclusive.jpg',
  marca: 'Mercedez Bens',
  modelo: 'C180',
  ano: 'ano: 1993',
  valor: 'valor: 180.000',
},
{
  id: 16,
  imagem: './img/Lamborghini-Murcielago-LP-640-6.avif',
  marca: 'Lamborghini',
  modelo: 'Murciélago',
  ano: 'ano: 2001',
  valor: 'valor: 700.000',
},
];
